all:
  hosts:
    node1:
      ansible_host: 142.93.203.233
  children:
    slurmservers:
      hosts:
        node1:
    slurmexechosts:
      hosts:
        node1:
    # slurmdbdservers group removed due to it being unused and causing errors